export const wsActions = {
  CONNECT: 'CONNECT',
  CONNECTED: 'CONNECTED',
  LEAVE: 'LEAVE',
  DISCONNECTED: 'DISCONNECTED',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  CODE: 'CODE',
  CURSOR: 'CURSOR',
  CHAT: 'CHAT',
  JOINED: 'JOINED',
  LEAVED_LIVE: 'LEAVED_LIVE',
};
